### ISSUE TITLE
Bereitstellen eines "Track" Objekts

### ISSUE THREAD

**Issue by chrisdutz** [dukecon/dukecon_server#1]
Momentan wird der Track lediglich über seinen Namen identifiziert. Ich hatte mich mit Gerd darüber unterhalten, dass es schön wäre, wenn man Tracks attribute zuweisen könnte (Farbe etc.). Dazu bräuchten wir einen getrennten Objekttyp.

**Comment by ascheman** [comment]
Bekommen wir das über den neuen Meta-Service?

**Comment by ascheman** [comment]
Aktuell nicht mehr nötig!
