### ISSUE TITLE
Server cache should be completely invalidated upon reload from DOAG

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_server#14]
TalkProvider needs to re-initialize the talks cache with an empty list when reloading the data from DOAG. Currently ```0c5682d9ee5a1c57769c8b26471e102e3e78d952``` does not recognize a moved talk due to the same ID (then omits it as duplicate).

**Comment by sippsack** [comment]
does this belong to #9

**Comment by ascheman** [comment]
Seems to be resolved by #4 (#35)?
