### ISSUE TITLE
Erweitern der Objekte um einen eindeutigen PrimaryKey

### ISSUE THREAD

**Issue by chrisdutz** [dukecon/dukecon_server#2]
Momentan werden Speaker scheinbar über ihren Namen mit einem Talk verknüpft. Das fühlt sich für mich eher schlecht an. Zwar ist die Wahrscheinlichkeit dass ein Name doppelt vorkommt, ich würde das Problem aber gerne ausschließen. Technische Schlüssel würden auch updates und abgleiche erleichtern. Schließlich kann man im offline mode oder beim Einsatz mehrerer clients evtl. Probleme bekommen.

**Comment by dasniko** [comment]
Momentan werden Speaker überhaupt nicht mit einem Talk verknüpft, sie sind einfach ein Objekt des Talk-Objektes. Da ist keine "Relation" da, da in den Ursprungsdaten auch keine Relation da ist.

**Comment by ascheman** [comment]
@chrisdutz Ist das noch relevant?

**Comment by ascheman** [comment]
Nicht mehr nötig!
