### ISSUE TITLE
Setup and configure PostgreSQL 

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_server#28]

**Comment by ascheman** [comment]
Started migration (or better parallel development) on new branch feature/postgres. Currently some integration tests still fail. Do you have time to check this?

**Comment by sippsack** [comment]
I hadn't time yet but will look into it in the next few days.

**Comment by sippsack** [comment]
postgresql and flyway are configured

to start server application against postgresql:
- mvn spring-boot:run -Dspring.profiles.active=postgresql

to test server application against postgresql:
- mvn test -Dspring.profiles.active=postgresql-test

h2 db will be used without profile "postgresql*" 
- In-Memory (jdbc:h2:mem:testdb)
- db console available: http://localhost:8080/develop/h2-console/
