### ISSUE TITLE
Stack Trace in Server when calling keycloak.json for the first time

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_server#29]
Prereq:

[keycloak.txt](https://github.com/dukecon/dukecon_server/files/33991/keycloak.txt)
- you are not logged in (clear cookies to be sure)
- load the html page
- in the server you see the stack trace attached

**Comment by sippsack** [comment]
@srose should have a look at this exception, I already invited him to our github project

**Comment by steffchep** [comment]
HAve not seen this in some time.... closing
