### ISSUE TITLE
Provide method to retrieve data status

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon_server#30]
Related to https://github.com/dukecon/dukecon_html5/issues/22:
It would be nice to be able to ask the server if there are changes in the data since a certain timestamp.

**Comment by sippsack** [comment]
@ascheman and I already discussed it. We could calculate a hash over the input json from DOAG and send you this. The client could persist this hash and compare with future requests.

Or should we use a http automatism for it, e. g. etag? I've no experiences with this.

**Comment by sippsack** [comment]
I've added http etag support to our REST configuration. Calling the REST service returns an etag value in the http header:

$ curl -s -D - -H "Content-Type: application/json" 'http://localhost:8080/devel
op/rest/conferences/499959/' -o /dev/null
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
ETag: "02a288e71103d29d262eec7e4e61d9a0c"
Content-Type: application/json;charset=UTF-8
Content-Length: 143047
Date: Sun, 06 Dec 2015 20:46:52 GMT

Further request can ask for a changed etag and get a 304 "Not modified" if this resource has not changed:

$ curl -s -D - -H "Content-Type: application/json" -H 'If-None-Match: "02a288e7
1103d29d262eec7e4e61d9a0c"' 'http://localhost:8080/develop/rest/conferences/499
959/' -o /dev/null
HTTP/1.1 304 Not Modified
Server: Apache-Coyote/1.1
ETag: "02a288e71103d29d262eec7e4e61d9a0c"
Date: Sun, 06 Dec 2015 20:52:45 GMT
