### ISSUE TITLE
Fehlertolerantes Holen der Daten von JL

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_server#4]
Aktuelles Problem: JavaLand-Backend liefert keine Daten. Das sollte tolerant behandelt werden (evtl. zusammen mit einem allgemeinen Caching, vgl. #3). 

Implementierungsidee: Hystrix

**Comment by sippsack** [comment]
Ich dachte der Server cached schon das doag json bzw. liefert eine gespeicherte Version aus.

Die doag hat das 2015er jetzt scheinbar vom Netz genommen. Die sollten uns erste mal eine dauerhafte test-url zur Verfügung stellen.

**Comment by ascheman** [comment]
Nö, solange niemand #3 löst, gibt's kein Caching ;-)

Werde natürlich auch nochmal bei der DOAG nachfragen, vielleicht war es nur ein Versehen? Frank hatte auch schon mal geklagt dass es nicht so stabil sei.

Aber wir sollten auch fehlertolerant werden ...

**Comment by sippsack** [comment]
Was soll denn passieren, wenn die hystrix Sicherung raus ist? Einfach die statische Variante aus #3 laden. Dann müssen wir in #3 die Daten auf dem Server nach jeder Änderung durch die doag automatisiert irgendwo fest ablegen (filesystem, db?). Also immer die Daten von der doag holen. Wenn die doag Daten nicht verfügbar sind, wird der letzte stand zurückgegeben.

**Comment by ascheman** [comment]
Ja, ungefähr so hätte ich mir das auch gedacht ...

**Comment by ahus1** [comment]
Adding volumes to https://github.com/dukecon/dukecon_server_docker/commit/c599644c8e048685c8b8d915c965c61d90a203bf

**Comment by ahus1** [comment]
habe mich mal drum gekümmert und mit PR #35 ein Beispiel zur Verfügung gestellt. Funktioniert zusammen mit den Ändeurngen in dukecon_server_docker und dukecon_infra. 

@ascheman / @sippsack (oder ein anderer Freiwilliger): freue mich über ein Review.

Den Timeout für Datenabruf bei DOAG habe ich auf 5 Sekunden festgelegt. Denkt ihr das ist OK?

**Comment by ahus1** [comment]
beide PRs sind gemerged. Schließen (wenn's vorher noch mal jemand testet?)

**Comment by ascheman** [comment]
Erledigt!
