### ISSUE TITLE
Admin-URL zum Cache-Invalidieren des DOAG-Inputs im Talk-Provider

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_server#8]

**Comment by ahus1** [comment]
URL available for refresh: `/rest/conferences/update/499959`

Open issues: you might need to add SSL CA of of SSL certificate at keycloak to you JVM. Redirects of Sprint Boot won't go to SSL.

**Comment by ahus1** [comment]
@ascheman / @chrisdutz fixed an issue with dukecon_server passing the link back to the app without SSL when accessing a secured backend server URL. This might make things easier inside the flex client. See 3d7c2abf5e66c1ece2995365864847554432d763
